name: Deploy Angular to Production

on:
  workflow_run:
    workflows: ["Discord Push Notification"]  
    types:
      - completed
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # or your preferred version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/gestion-des-transports-front/browser/*"
          target: "/var/www/covoit"
          strip_components: 3
          overwrite: true
          
      - name: Fix permissions
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo chown -R www-data:www-data /var/www/covoit
            sudo chmod -R 755 /var/www/covoit

      - name: Send Discord deploy notification
        if: success()
        run: |
          PAYLOAD=$(cat <<EOF
          {
            "embeds": [{
              "title": "🚀 FRONTEND Deployment Successful !  😎",
              "description": "\n[🔗 Visit the site](https://covoit.goegilles.fr/)",
              "color": 15410111,
              "thumbnail": {
                "url": "https://goegilles.fr/logo.png"
              }
            }]
          }
          EOF
          )
          curl -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"

      - name: Send Discord failure notification
        if: failure()
        run: |
          PAYLOAD=$(cat <<EOF
          {
            "embeds": [{
              "title": "💥 Deployment Failed",
              "description": "Something went wrong with the deployment... 😢\n\nCheck the [GitHub Actions logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})",
              "color": 15158332,
              "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%S.000Z)"
            }]
          }
          EOF
          )
          curl -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"
